### ISSUE TITLE
Incompatibility with CensoredASM/loliASM

### ISSUE THREAD

**Issue by iekiekkeikei** [Polyfrost/PolyPatcher#22]
Crashes when used with CensoredASM/loliASM
Crashreport : https://mclo.gs/FqjWYLT

**Comment by Wyvest** [comment]
Does this happen with normal Patcher? Also, make a ticket at discord.gg/polyfrost and i can troubleshoot this further.

**Comment by iekiekkeikei** [comment]
yes, this happens with normal Patcher.
crashreport : https://mclo.gs/2QiyIWj

**Comment by RoyalQX** [comment]
Changing "optimizeRegistries" in the CensoredASM config to false is a workaround for now.

**Comment by Wyvest** [comment]
Will be released in the next day or two
