### ISSUE TITLE
Crash with BetterFPS

### ISSUE THREAD

**Issue by HowardZHY** [Polyfrost/PolyPatcher#24]
https://github.com/Guichaguri/BetterFps

Only Tested 1.8.9
https://mclo.gs/WUTzKr2

**Comment by HowardZHY** [comment]
If this mod merged BetterFPS plz make a notice to let ppl remove it

**Comment by MicrocontrollersDev** [comment]
Considering BetterFPS can get you banned on practically any server with any anticheat I personally don't think it's worthwhile to fix this

**Comment by HowardZHY** [comment]
> Considering BetterFPS can get you banned on practically any server with any anticheat I personally don't think it's worthwhile to fix this

I've be using it for years, it won't cause anything wrong if you don't use Taylor Algorithm

**Comment by MicrocontrollersDev** [comment]
i refuse to use the mod if it has the slightest chance of causing me to get banned. optifine fast math is extremely tame yet some servers detect and kick players who use it. regardless with modern cpu cache sizes I dont think the vanilla LUT is big enough to argue it's a necessary risk in the first place. if anything it would make more sense for polypatcher to optimize the LUT in a vanilla compatible fashion (for example cos(-x) = cos(x), sin(-x) = -sin(x))

**Comment by Wyvest** [comment]
We are not supporting BetterFPS.

**Comment by MicrocontrollersDev** [comment]
> If this mod merged BetterFPS plz make a notice to let ppl remove it

in recent commits an optimized math lut was implemented as described above that is 100% vanilla compatible.
