### ISSUE TITLE
Able to launch with patcher but not with polypatcher

### ISSUE THREAD

**Issue by Zacgamingproalt** [Polyfrost/PolyPatcher#27]
I have a large modpack that works with patcher but doesnt work with polypatcher. Also I'm using windows 11 (for some reason it says 10 in the log)
[crash-2024-06-27_13.22.52-client.txt](https://github.com/user-attachments/files/16012606/crash-2024-06-27_13.22.52-client.txt)

**Comment by Wyvest** [comment]
You’re pairing 1.8.9 mods with 1.12.2 mods.

**Comment by Zacgamingproalt** [comment]
whoops

**Comment by Zacgamingproalt** [comment]
> You’re pairing 1.8.9 mods with 1.12.2 mods.
Which mods? The game launches without polypatcher and im sure that the version of poly patcher that I installed is 1.8.9.
Let me send one with poly patcher and one with patcher
[Poly Patcher Crash Log](https://github.com/user-attachments/files/16012960/crash-2024-06-27_13.52.38-client.txt)
[Patcher Log](https://github.com/user-attachments/files/16013010/latest.log)
The exact same mods just changing patcher and poly patcher

**Comment by Wyvest** [comment]
Make a ticket at discord.gg/polyfrost
