### ISSUE TITLE
Change ModId

### ISSUE THREAD

**Issue by j10a1n15** [Polyfrost/PolyPatcher#29]
The modid is still patcher
Could you maybe please change it to polypatcher
Thank u

**Comment by Wyvest** [comment]
why?

**Comment by j10a1n15** [comment]
Why not,
Its a mod thats different from Patcher. It has its own name, different code and more
It feels weird to keep the modid the same
Also it needs to be different for the modchecker in pss

**Comment by Wyvest** [comment]
> Why not, Its a mod thats different from Patcher. It has its own name, different code and more It feels weird to keep the modid the same Also it needs to be different for the modchecker in pss

Replacing the mod id will break all other mods that attempt to support Patcher (https://github.com/search?q=Loader.isModLoaded%28%22patcher%22%29&type=code). We send a separate mod id to servers ("polypatcher") as well. If you want to detect PolyPatcher specifically, there are two classes (`club.sk1er.patcher.PolyPatcher` and `club.sk1er.patcher.config.OldPatcherConfig`) that aren't in the original mod and will stay in PolyPatcher as a backwards compat thing.
