### ISSUE TITLE
Performance improvement: beacon beams are rendered twice per frame

### ISSUE THREAD

**Issue by MicrocontrollersDev** [Polyfrost/PolyPatcher#38]
relevant mojira issue: https://bugs.mojang.com/browse/MC-112730

Confirmed in 1.8.9 by myself. Fixing this will change the look of the beacon beam so should be a toggle. This fix is also in Debugify: [this way](https://github.com/isXander/Debugify/blob/68fa311ddc656e62d83bd8709c3c550a8a59ea65/src/client/java/dev/isxander/debugify/client/mixins/basic/mc112730/ChunkRenderDispatcherRenderChunkRebuildTaskMixin.java) and later [this way](https://github.com/isXander/Debugify/blob/1.21/src/client/java/dev/isxander/debugify/client/mixins/basic/mc112730/SectionCompilerMixin.java)

**Comment by Wyvest** [comment]
Looks like https://github.com/MinecraftForge/MinecraftForge/pull/3651 also fixes this issue
