### ISSUE TITLE
Particles (and apparently sounds) come from last position

### ISSUE THREAD

**Issue by MicrocontrollersDev** [Polyfrost/PolyPatcher#42]
Haven't noticed the issue with sounds but its clear that particles dont render correctly when in spectator mode. Forge has a fix for this, but this seems more complicated than I am able to do.

Forge's fix can be found here: https://github.com/MinecraftForge/MinecraftForge/pull/4728

Mojira issue: https://bugs.mojang.com/browse/MC-46445

**Comment by Wyvest** [comment]
Make this a suggestion in the discord
