### ISSUE TITLE
Why are certain options marked as deprecated?

### ISSUE THREAD

**Issue by Aetopia** [Polyfrost/PolyPatcher#49]
![2024-07-15_17 41 27](https://github.com/user-attachments/assets/a592a997-a78b-4be8-b94b-5a800aad0005)
![2024-07-15_17 41 29](https://github.com/user-attachments/assets/26b807b4-c81b-46fb-ae0c-c8cbdfa31cc5)

As the screenshots, showcase, these options have been marked as deprecated.
But they work as intended with the OG Patcher, was there any reason to deprecate these options?

**Comment by Wyvest** [comment]
They are replaced by the mods listed in the description.
