### ISSUE TITLE
Incompatible with OpenJ9

### ISSUE THREAD

**Issue by ALJ323** [Polyfrost/PolyPatcher#69]
Mod is unusable when using OpenJ9 (which is used for lower memory consumption at the cost of speed), only seeming to function on OpenJDK/Hotspot.

Tested with IBM Semeru OpenJ9 JRE 8.0.412.8 & Eclipse Adoption OpenJDK /w Hotspot 8.0.422.5
Using Polypatcher v.1.10.0 with all other mods disabled on Forge 2860.
[crash-2024-07-24_10.22.13-client.txt](https://github.com/user-attachments/files/16365609/crash-2024-07-24_10.22.13-client.txt)

(Also tested on Cleanroom /w GraalVM, in which its unable to get as far as downloading/implementing OneConfig)

**Comment by Wyvest** [comment]
unfortunately, the current oneconfig v0 api is only compatible with OpenJDK. V1 will support J9, or at least try to

**Comment by Wyvest** [comment]
Closing as this is a larger issue of OneConfig V0. V1 should fix this
