### ISSUE TITLE
Incompatible with FermiumASM

### ISSUE THREAD

**Issue by ALJ323** [Polyfrost/PolyPatcher#70]
Mod crashes on load when using FermiumASM (normalASM)
(Functions properly when using loliASM/censoredASM)
https://mclo.gs/xP62UYm

**Comment by Wyvest** [comment]
Are there any other mods like CensoredASM or NormalASM i should be aware of before I fix the issue

**Comment by ALJ323** [comment]
in this case i was testing with other performance & mixin reliant mods, such as Universal Tweaks, VintageFix, and even Optifine, however NormalASM was the only trigger that caused a crash early in loading while testing suspects thus far.

**Comment by Wyvest** [comment]
Well, Normal seems to be a fork of CensoredASM. Are there any other forks?

**Comment by ALJ323** [comment]
Not that I am aware of that are relevant, no.

**Comment by Wyvest** [comment]
aight
fixed in https://github.com/Polyfrost/PolyPatcher/commit/ea903ba587dc862210f233037a3c814eaa437740
