### ISSUE TITLE
Incompatibility with both HEI & JEI, General Compatibility question

### ISSUE THREAD

**Issue by ALJ323** [Polyfrost/PolyPatcher#71]
Crashes when installed alongside Had Enough Items
https://mclo.gs/dUiubkE

Also tested with the original JEI mod and only performance mods.
https://mclo.gs/wmLmbge

There were numerous other crashes with other mods, ranging from ones that mess with the player model, to ones that simply add new systems, and even ones that add minor additions like new items, weapons, or foods, that it would be difficult to isolate the cause in a crash report outside of stating each individual one encountered. 
Is this PolyPatcher intended only to support (mostly) Vanilla Minecraft?

**Comment by Wyvest** [comment]
No, it is meant to work with other mods.

Also, you seem to be bug searching... make a ticket at discord.gg/polyfrost so we can track this easily

**Comment by ALJ323** [comment]
Will try to figure out the registration process for this service momentarily

**Comment by Wyvest** [comment]
Please make a ticket so we can troubleshoot this further.
