### ISSUE TITLE
java.lang.NullPointerException: Batching chunks

### ISSUE THREAD

**Issue by TheDGOfficial** [Polyfrost/PolyPatcher#73]
Just got this game crash today:

```java
java.lang.NullPointerException: Batching chunks
	at net.minecraft.client.renderer.chunk.RenderChunk.redirect$zln000$patcher$renderSpecialTileEntitiesOnce(RenderChunk.java:914)
	at net.minecraft.client.renderer.chunk.RenderChunk.rebuildChunk(RenderChunk.java:257)
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.processTask(SourceFile:78)
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.run(SourceFile:38)
	at java.lang.Thread.run(Thread.java:750)
```

I'm guessing it is because of null being returned from the method `getSpecialRenderer` and the call to `forceTileEntityRender` without a null check in the Mixin `RenderChunkMixin_OptimizeSpecialTileEntities` (NPE probably happens at line 25 specifically, can't be sure cause the line number 914 doesn't help from Stacktrace since its injected code but I think NPE can't happen in any other line unless `TileEntityRendererDispatcher.instance` is null. The call to `getSpecialRenderer`  is at line 24):

https://github.com/Polyfrost/PolyPatcher/blob/b27402b10e1f08263949b2155f6fc005a03a23ac/src/main/java/club/sk1er/patcher/mixins/performance/RenderChunkMixin_OptimizeSpecialTileEntities.java#L22-L26

The result of null return value from `getSpecialRenderer` might be from the Mixin `TileEntityRendererDispatcherMixin_RemoveInvalidEntities` (line 17 specifically):

https://github.com/Polyfrost/PolyPatcher/blob/b27402b10e1f08263949b2155f6fc005a03a23ac/src/main/java/club/sk1er/patcher/mixins/performance/TileEntityRendererDispatcherMixin_RemoveInvalidEntities.java#L14-L19

However, that being said, I am not sure at all if the `TileEntityRendererDispatcherMixin_RemoveInvalidEntities` caused the null return value or if vanilla can return null by itself in the `getSpecialRenderer` as well, and I don't know if the game would crash somewhere else or not if it didn't at `RenderChunkMixin_OptimizeSpecialTileEntities` mixin.

**Comment by Wyvest** [comment]
Lmao we broke our own mixin

**Comment by Wyvest** [comment]
I'll fix it soon
