### ISSUE TITLE
Incompatibility with Had Enough Items

### ISSUE THREAD

**Issue by Moonyol** [Polyfrost/PolyPatcher#75]
If polypatcher is installed then hadenoughitems will not load (its not in the mods menu)
![image](https://github.com/user-attachments/assets/f2112f1e-110f-4252-a3e4-57b58ff86f61)
log: https://pastebin.com/1sg8GWag

**Comment by Wyvest** [comment]
Can you make a ticket at discord.gg/polyfrost
